# Generated by Django 3.2.7 on 2021-09-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=31, null=True)),
                ('fullname', models.CharField(blank=True, max_length=127, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=511, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
