# Generated by Django 3.2.7 on 2021-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210909_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
